name: CI

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install

      #- name: DATABASE_URL
      #  run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Clear database
        env: ${{ secrets.DATABASE_URL}}
        run: poetry run pyhton3 src/db_helper.py
      
      #- name: Clear database
      #  run: poetry run python3 src/db_helper.py
      - name: Run robot tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: bash run_robot_tests.sh
